### PR TITLE
Add Android 6.0.1 R30 changelog

### PR DESCRIPTION
**Pull request by andi34**
- r17 was used as base, using other tags as base results in
  a nightmare of histroy mix

### CODE REVIEW

**Comment by andi34** [comment]
@novado i wasn't able to find the correct base tag for r31 yet, maybe you have more luck

Here's what i have tested, but look at the size.... thx google for making stuff complicated:

376135 Apr 12 23:24 android-6.0.1_r1-to-android-6.0.1_r31.html
382104 Apr 12 23:20 android-6.0.1_r10-to-android-6.0.1_r31.html
381480 Apr 12 23:19 android-6.0.1_r11-to-android-6.0.1_r31.html
381578 Apr 12 23:19 android-6.0.1_r12-to-android-6.0.1_r31.html
382435 Apr 12 23:18 android-6.0.1_r13-to-android-6.0.1_r31.html
 32978 Apr 12 23:16 android-6.0.1_r17-to-android-6.0.1_r30.html
385014 Apr 12 23:16 android-6.0.1_r17-to-android-6.0.1_r31.html
697729 Apr 12 23:16 android-6.0.1_r22-to-android-6.0.1_r30.html
838713 Apr 12 23:16 android-6.0.1_r22-to-android-6.0.1_r31.html
705084 Apr 12 23:16 android-6.0.1_r24-to-android-6.0.1_r30.html
846068 Apr 12 23:15 android-6.0.1_r24-to-android-6.0.1_r31.html
376572 Apr 12 23:23 android-6.0.1_r3-to-android-6.0.1_r31.html
396704 Apr 12 23:14 android-6.0.1_r30-to-android-6.0.1_r31.html
379643 Apr 12 23:21 android-6.0.1_r7-to-android-6.0.1_r31.html
380006 Apr 12 23:21 android-6.0.1_r8-to-android-6.0.1_r31.html
382004 Apr 12 23:20 android-6.0.1_r9-to-android-6.0.1_r31.html

**Comment by andi34** [comment]
A small sidenote: seems like some 6.0 changelogs aren't added to index.html yet ;)

**Comment by danybony** [comment]
@andi34 how are you finding the base tag for a new one?
The use of different bases makes the creation of changelogs very tricky

**Comment by andi34** [comment]
@danybony i created a changelog from earlier tags and looked which of them makes really sense (on build repo you will most of the time see if It's a "good" or "bad" changelog).

As you can see here
https://dl.srvr.tech/aosp-changelog/test/
None of the changelogs makes sense besides the one from r17 to r30.

For 6.0.1 r31 i think Google again used a 5.1 tag, maybe an old 6.0.0 as base, no created changelog from earlier 6.0.1 tag makes sense.

**Comment by danybony** [comment]
@andi34 for android-6.0.1_r31 did you try generating one from android-6.0.1_r18?
Using the following command seems to give us a decent result for the parent tag for a given one:
`git describe --abbrev=0 --tags android-6.0.1_r30^`

This PR however LGTM

**Comment by andi34** [comment]
No, didn't niticed r18 XD can do in the evening if you like

**Comment by danybony** [comment]
Thanks @andi34, it's there already 😉 https://github.com/novoda/aosp.changelog.to/pull/10

**Pull request merged**
